{
    "name": "OdooCMS Student Portal",
    'version': '12.0',
    'license': 'LGPL-3',
    'category': 'OdooCMS',
    'sequence': 3,
    'summary': "Student Portal Module of OdooCMS""",
    'author': 'AARSOL',
    'company': 'AARSOL',
    'website': "http://www.aarsol.com/",
    'description': 'An easy and efficient management tool for Student Portal',
    
    'depends': ['portal','odoocms','odoocms_exam','odoocms_fee','odoocms_attendance'],
    'data': [
        'security/ir.model.access.csv',
        'views/assets.xml',
        'views/student_portal_templates.xml',
        'views/request_student_profile.xml',
        'views/student_course_templates.xml',
        'views/student_result_templates.xml',
        'views/student_semester_freeze_templates.xml',
        'views/student_semester_unfreeze_templates.xml',
        'views/student_subject_witdraw_templates.xml',
        'views/request_subject_withdraw_view.xml',
        'views/student_semester_planing_templates.xml',
        'views/student_merit_info_template.xml',
        #'views/student_view.xml',
        
    ],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
