
{
    "name": "OdooCMS Fee",
    'version': '12.0',
    'license': 'LGPL-3',
    'category': 'OdooCMS',
    'sequence': 3,
    'summary': "Fee Management Module of OdooCMS""",
    'author': 'AARSOL',
    'company': 'AARSOL',
    'website': "http://www.aarsol.com/",
    "depends": ['account', 'odoocms', 'odoocms_admission'],
    "data": [
        'data/account_data.xml',
        'security/odoocms_fee_security.xml',
        'security/ir.model.access.csv',
        'menu/fee_menu_view.xml',
        
        'views/fee_structure.xml',
        'views/fee_types.xml',
        'views/fee_category.xml',
        'views/fee_register.xml',
        'views/fee_journal_dashboard_view.xml',
        'views/fee_journal_inherit.xml',
        'views/student_view.xml',
        'views/account_invoice_view.xml',
        
        'wizard/generate_challan_view.xml',
        'wizard/split_challan_view.xml',
        'wizard/process_fee_payment_view.xml',
        'wizard/program_wise_fin_summary_wiz_view.xml',
        'wizard/student_dues_warning_letter_wiz_view.xml',
        'wizard/receipt_received_summary_wiz_view.xml',
        'wizard/receipt_received_detail_wiz_view.xml',
        'wizard/student_fin_report_summary_wiz_view.xml',
        
        'report/report_invoice.xml',
        'report/program_wise_fin_summary_report.xml',
        'report/student_dues_warning_letter_report.xml',
        'report/receipt_received_summary_report.xml',
        'report/receipt_received_detail_report.xml',
        'report/student_fin_report_summary_report.xml',
        'report/report.xml',
    ],
    "installable": True,
    "auto_install": False,
    'application': True,
}
